version: "3.8"
services:
  app1:
    build:
      context: ./app
      dockerfile: Dockerfile
    networks:
      - app-network
  app2:
    build:
      context: ./app
      dockerfile: Dockerfile
    networks:
      - app-network
  app3:
    build:
      context: ./app
      dockerfile: Dockerfile
    networks:
      - app-network
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - app1
      - app2
      - app3
networks:
  app-network:
    driver: bridge
