CREATE TABLE IF NOT EXISTS access_log (
  id INT AUTO_INCREMENT PRIMARY KEY,
  access_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  client_ip VARCHAR(45) NOT NULL,
  internal_ip VARCHAR(45) NOT NULL
);
