FROM python:3.9

WORKDIR /app

# Copy application code
COPY app.py .

# Copy requirements.txt and install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Run the app
CMD ["python", "app.py"]
